image: node:9

pipelines:
  branches:
    master:
      - step:
          name: Build
          caches:
            - node
          script:
            - npm install -g npm latest; npm ci
            - npm run build
          artifacts:
            - dist/**
      - step:
          name: Publish
          deployment: test
          script:
            - task: atlassian/scp-deploy:0.1.0
              environment:
                USER: "kaisky89"
                SERVER: "213.136.78.46"
                REMOTE_PATH: "public_html/ga-spendenquittungen"
                LOCAL_PATH: "dist/*"
                EXTRA_ARGS: "-C -P 48008"