image: node:9

pipelines:
  branches:
    master:
      - step:
          name: Build
          caches:
            - node
          script:
            - npm install -g npm latest; npm ci; npm rebuild node-sass
            - npm run build
          artifacts:
            - dist/**
      - step:
          name: Publish
          deployment: test
          script:
            - ssh-keyscan -p 48008 -H 213.136.78.46 >> ~/.ssh/known_hosts
            - scp -rp -C -P 48008 dist/* kaisky89@213.136.78.46:public_html/ga-spendenquittungen