name: 'Lint'
description: 'Lint using ESLint and Prettier'

runs:
  using: 'composite'
  steps:
    - name: Lint
      run: npm run lint
      shell: bash
    # - name: Check Formatting
    #   run: npm run lint:prettier
    #   shell: bash
